// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function AddFlashcard(arg1:string,arg2:string):Promise<Array<model.Flashcard>>;

export function DeleteFlashcard(arg1:string):Promise<Array<model.Flashcard>>;

export function GetFlashcards():Promise<Array<model.Flashcard>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateFlashcard(arg1:model.Flashcard):Promise<Array<model.Flashcard>>;
