// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFlashcard(arg1, arg2) {
  return window['go']['controller']['FlashcardController']['AddFlashcard'](arg1, arg2);
}

export function DeleteFlashcard(arg1) {
  return window['go']['controller']['FlashcardController']['DeleteFlashcard'](arg1);
}

export function GetFlashcards() {
  return window['go']['controller']['FlashcardController']['GetFlashcards']();
}

export function Startup(arg1) {
  return window['go']['controller']['FlashcardController']['Startup'](arg1);
}

export function UpdateFlashcard(arg1) {
  return window['go']['controller']['FlashcardController']['UpdateFlashcard'](arg1);
}
