// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEntry(arg1, arg2, arg3) {
  return window['go']['controller']['JournalController']['CreateEntry'](arg1, arg2, arg3);
}

export function DeleteEntry(arg1) {
  return window['go']['controller']['JournalController']['DeleteEntry'](arg1);
}

export function GetEntries() {
  return window['go']['controller']['JournalController']['GetEntries']();
}

export function Startup(arg1) {
  return window['go']['controller']['JournalController']['Startup'](arg1);
}

export function UpdateEntry(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['JournalController']['UpdateEntry'](arg1, arg2, arg3, arg4);
}
