// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateEntry(arg1:string,arg2:string,arg3:string):Promise<models.JournalEntry>;

export function DeleteEntry(arg1:string):Promise<void>;

export function GetEntries():Promise<Array<models.JournalEntry>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateEntry(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.JournalEntry>;
