// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMemo(arg1, arg2) {
  return window['go']['controller']['MemoController']['AddMemo'](arg1, arg2);
}

export function DeleteMemo(arg1) {
  return window['go']['controller']['MemoController']['DeleteMemo'](arg1);
}

export function GetMemos() {
  return window['go']['controller']['MemoController']['GetMemos']();
}

export function Startup(arg1) {
  return window['go']['controller']['MemoController']['Startup'](arg1);
}

export function UpdateMemo(arg1) {
  return window['go']['controller']['MemoController']['UpdateMemo'](arg1);
}
