// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function AddMemo(arg1:string,arg2:string):Promise<Array<model.StickyNote>>;

export function DeleteMemo(arg1:string):Promise<Array<model.StickyNote>>;

export function GetMemos():Promise<Array<model.StickyNote>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateMemo(arg1:model.StickyNote):Promise<Array<model.StickyNote>>;
