// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function GetTodayIbadah():Promise<model.DailyIbadah>;

export function GetWeeklyStats():Promise<Array<model.DailyIbadah>>;

export function SaveIbadah(arg1:model.DailyIbadah):Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;
