// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTodayIbadah() {
  return window['go']['controller']['MuslimController']['GetTodayIbadah']();
}

export function GetWeeklyStats() {
  return window['go']['controller']['MuslimController']['GetWeeklyStats']();
}

export function SaveIbadah(arg1) {
  return window['go']['controller']['MuslimController']['SaveIbadah'](arg1);
}

export function Startup(arg1) {
  return window['go']['controller']['MuslimController']['Startup'](arg1);
}
