// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEntries() {
  return window['go']['controller']['NoFapController']['GetEntries']();
}

export function GetStats() {
  return window['go']['controller']['NoFapController']['GetStats']();
}

export function GetTodayLog() {
  return window['go']['controller']['NoFapController']['GetTodayLog']();
}

export function LogToday(arg1, arg2, arg3) {
  return window['go']['controller']['NoFapController']['LogToday'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['controller']['NoFapController']['Startup'](arg1);
}
