// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function GetEntries():Promise<Array<model.NoFapEntry>>;

export function GetStats():Promise<model.NoFapStats>;

export function GetTodayLog():Promise<model.NoFapEntry>;

export function LogToday(arg1:string,arg2:number,arg3:string):Promise<model.NoFapStats>;

export function Startup(arg1:context.Context):Promise<void>;
