// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';
import {context} from '../models';

export function GetPomodoroData():Promise<controller.PomodoroDashboardData>;

export function RecordSession(arg1:number):Promise<controller.PomodoroDashboardData>;

export function Startup(arg1:context.Context):Promise<void>;
