// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPomodoroData() {
  return window['go']['controller']['PomodoroController']['GetPomodoroData']();
}

export function RecordSession(arg1) {
  return window['go']['controller']['PomodoroController']['RecordSession'](arg1);
}

export function Startup(arg1) {
  return window['go']['controller']['PomodoroController']['Startup'](arg1);
}
