// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1, arg2) {
  return window['go']['controller']['ResourceController']['AddFolder'](arg1, arg2);
}

export function AddItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['controller']['ResourceController']['AddItem'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteFolder(arg1) {
  return window['go']['controller']['ResourceController']['DeleteFolder'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['controller']['ResourceController']['DeleteItem'](arg1);
}

export function GetData() {
  return window['go']['controller']['ResourceController']['GetData']();
}

export function Startup(arg1) {
  return window['go']['controller']['ResourceController']['Startup'](arg1);
}

export function UpdateFolder(arg1, arg2, arg3) {
  return window['go']['controller']['ResourceController']['UpdateFolder'](arg1, arg2, arg3);
}

export function UpdateItem(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['ResourceController']['UpdateItem'](arg1, arg2, arg3, arg4);
}
