// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';
import {context} from '../models';

export function AddFolder(arg1:string,arg2:string):Promise<repository.ResourceData>;

export function AddItem(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<repository.ResourceData>;

export function DeleteFolder(arg1:string):Promise<repository.ResourceData>;

export function DeleteItem(arg1:string):Promise<repository.ResourceData>;

export function GetData():Promise<repository.ResourceData>;

export function OpenFile(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateFolder(arg1:string,arg2:string,arg3:string):Promise<repository.ResourceData>;

export function UpdateItem(arg1:string,arg2:string,arg3:string,arg4:string):Promise<repository.ResourceData>;
