// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';
import {context} from '../models';

export function GetUserProfile():Promise<controller.UserProfile>;

export function Startup(arg1:context.Context):Promise<void>;
