// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserProfile() {
  return window['go']['controller']['SystemController']['GetUserProfile']();
}

export function Startup(arg1) {
  return window['go']['controller']['SystemController']['Startup'](arg1);
}

export function UpdateAvatar() {
  return window['go']['controller']['SystemController']['UpdateAvatar']();
}

export function UpdateUserProfile(arg1, arg2, arg3) {
  return window['go']['controller']['SystemController']['UpdateUserProfile'](arg1, arg2, arg3);
}
