// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['controller']['TaskController']['AddTask'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteTask(arg1) {
  return window['go']['controller']['TaskController']['DeleteTask'](arg1);
}

export function GetTasks() {
  return window['go']['controller']['TaskController']['GetTasks']();
}

export function Startup(arg1) {
  return window['go']['controller']['TaskController']['Startup'](arg1);
}

export function ToggleHoliday(arg1) {
  return window['go']['controller']['TaskController']['ToggleHoliday'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['controller']['TaskController']['UpdateTask'](arg1);
}
