// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function MinimizeWindow():Promise<void>;

export function SetFullMode():Promise<void>;

export function SetMiniMode():Promise<void>;
